spring.datasource.url=jdbc:postgresql://ep-aged-sound-agjvrv0z-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_e98UHmDIrGop
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
